name: Test All Combinations

on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sunday at 2 AM UTC

jobs:
  test-combinations:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3 hours max

    strategy:
      fail-fast: false
      matrix:
        php: ['8.1', '8.2', '8.3']
        civicrm: ['6.5.1', '6.6.3', '6.7.1', 'master']

    name: PHP ${{ matrix.php }} + CiviCRM ${{ matrix.civicrm }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image with PHP ${{ matrix.php }}
        run: |
          PHP_VERSION=${{ matrix.php }} docker-compose build --no-cache

      - name: Start containers
        env:
          PHP_VERSION: ${{ matrix.php }}
          CIVICRM_VERSION: ${{ matrix.civicrm }}
          CIVICRM_SITE_TYPE: drupal10-demo
        run: |
          docker-compose up -d

      - name: Wait for site to be ready
        run: |
          echo "Waiting for site to become accessible..."
          max_attempts=60
          attempt=0
          while [ $attempt -lt $max_attempts ]; do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080 | grep -q "200\|302"; then
              echo "✓ Site is accessible"
              break
            fi
            attempt=$((attempt + 1))
            echo "Waiting... ($attempt/$max_attempts)"
            sleep 10
          done

          if [ $attempt -eq $max_attempts ]; then
            echo "✗ Site failed to become accessible"
            docker-compose logs civicrm
            exit 1
          fi

      - name: Run Playwright tests
        env:
          SKIP_WEBSERVER: 1
        run: npm test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-php${{ matrix.php }}-civicrm${{ matrix.civicrm }}
          path: |
            test-results/
            playwright-report/
          retention-days: 7

      - name: Show logs on failure
        if: failure()
        run: |
          echo "=== CiviCRM Container Logs ==="
          docker-compose logs civicrm
          echo "=== MySQL Container Logs ==="
          docker-compose logs mysql

      - name: Stop containers
        if: always()
        run: docker-compose down -v

  summary:
    needs: test-combinations
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Test Matrix Summary
        run: |
          echo "## Test Matrix Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| PHP | CiviCRM | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|---------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| All | All     | ${{ needs.test-combinations.result }} |" >> $GITHUB_STEP_SUMMARY
